using System.Collections.Generic;
using UnityEngine.InputSystem;

namespace KeyInputVR.KeyMaps
{
    public class GermanKeyMap : IKeyMap
    {
        Dictionary<Key, KeyDefinition> IKeyMap.GetKeyMap()
        {
            return _keyMap;
        }

        private readonly Dictionary<Key, KeyDefinition> _keyMap = new Dictionary<Key, KeyDefinition>()
        {
            {Key.None, new KeyDefinition(Key.None, "")},
            {Key.Space, new KeyDefinition(Key.Space, "\u02FD")},
            {Key.Enter, new KeyDefinition(Key.Enter, "Enter")},
            {Key.Tab, new KeyDefinition(Key.Tab, "Tab")},
            {Key.Backquote, new KeyDefinition("^","°")},
            {Key.Quote, new KeyDefinition("ä", "Ä")},
            {Key.Semicolon, new KeyDefinition("ö", "Ö")},
            {Key.Comma, new KeyDefinition(",", ";")},
            {Key.Period, new KeyDefinition(".", ":")},
            {Key.Slash, new KeyDefinition("-", "_")},
            {Key.Backslash, new KeyDefinition("#", "'")},
            {Key.LeftBracket, new KeyDefinition("ü", "Ü")},
            {Key.RightBracket, new KeyDefinition("+", "*")},
            {Key.Minus, new KeyDefinition("ß", "?")},
            {Key.Equals, new KeyDefinition("\u00b4", "`")},
            {Key.A, new KeyDefinition("a", "A")},
            {Key.B, new KeyDefinition("b", "B")},
            {Key.C, new KeyDefinition("c", "C")},
            {Key.D, new KeyDefinition("d", "D")},
            {Key.E, new KeyDefinition("e", "E")},
            {Key.F, new KeyDefinition("f", "F")},
            {Key.G, new KeyDefinition("g", "G")},
            {Key.H, new KeyDefinition("h", "H")},
            {Key.I, new KeyDefinition("i", "I")},
            {Key.J, new KeyDefinition("j", "J")},
            {Key.K, new KeyDefinition("k", "K")},
            {Key.L, new KeyDefinition("l", "L")},
            {Key.M, new KeyDefinition("m", "M")},
            {Key.N, new KeyDefinition("n", "N")},
            {Key.O, new KeyDefinition("o", "O")},
            {Key.P, new KeyDefinition("p", "P")},
            {Key.Q, new KeyDefinition("q", "Q")},
            {Key.R, new KeyDefinition("r", "R")},
            {Key.S, new KeyDefinition("s", "S")},
            {Key.T, new KeyDefinition("t", "T")},
            {Key.U, new KeyDefinition("u", "U")},
            {Key.V, new KeyDefinition("v", "V")},
            {Key.W, new KeyDefinition("w", "W")},
            {Key.X, new KeyDefinition("x", "X")},
            {Key.Y, new KeyDefinition("z", "Z")},
            {Key.Z, new KeyDefinition("y", "Y")},
            {Key.Digit1, new KeyDefinition("1", "!")},
            {Key.Digit2, new KeyDefinition("2", "\"")},
            {Key.Digit3, new KeyDefinition("3", "§")},
            {Key.Digit4, new KeyDefinition("4", "$")},
            {Key.Digit5, new KeyDefinition("5", "%")},
            {Key.Digit6, new KeyDefinition("6", "&")},
            {Key.Digit7, new KeyDefinition("7", "/")},
            {Key.Digit8, new KeyDefinition("8", "(")},
            {Key.Digit9, new KeyDefinition("9", ")")},
            {Key.Digit0, new KeyDefinition("0", "=")},
            {Key.LeftShift, new KeyDefinition(Key.LeftShift, "Shift")},
            {Key.RightShift, new KeyDefinition(Key.RightShift, "Shift")},
            {Key.LeftAlt, new KeyDefinition(Key.LeftAlt, "Alt")},
            {Key.AltGr, new KeyDefinition(Key.AltGr, "Alt Gr")},
            {Key.LeftCtrl, new KeyDefinition(Key.LeftCtrl, "Strg")},
            {Key.RightCtrl, new KeyDefinition(Key.RightCtrl, "Strg")},
            {Key.LeftMeta, new KeyDefinition(Key.LeftMeta ,"Meta")},
            {Key.RightMeta, new KeyDefinition(Key.RightMeta, "Meta")},
            {Key.ContextMenu, new KeyDefinition(Key.ContextMenu, "Menu")},
            {Key.Escape, new KeyDefinition(Key.Escape, "Esc")},
            {Key.LeftArrow, new KeyDefinition(Key.LeftArrow, "←")},
            {Key.RightArrow, new KeyDefinition(Key.RightArrow, "→")},
            {Key.UpArrow, new KeyDefinition(Key.UpArrow, "↑")},
            {Key.DownArrow, new KeyDefinition(Key.DownArrow, "↓")},
            {Key.Backspace, new KeyDefinition(Key.Backspace, "←")},
            {Key.PageDown, new KeyDefinition(Key.PageDown, "Bild↓")},
            {Key.PageUp, new KeyDefinition(Key.PageUp, "Bild↑")},
            {Key.Home, new KeyDefinition(Key.Home, "Pos 1")},
            {Key.End, new KeyDefinition(Key.End, "End")},
            {Key.Insert, new KeyDefinition(Key.Insert, "Einf")},
            {Key.Delete, new KeyDefinition(Key.Delete, "Entf")},
            {Key.CapsLock, new KeyDefinition(Key.CapsLock, "Caps")},
            {Key.NumLock, new KeyDefinition(Key.NumLock, "Num")},
            {Key.PrintScreen, new KeyDefinition(Key.PrintScreen, "Drck")},
            {Key.ScrollLock, new KeyDefinition(Key.ScrollLock, "Rolln")},
            {Key.Pause, new KeyDefinition(Key.Pause, "Paus")},
            {Key.NumpadEnter, new KeyDefinition(Key.NumpadEnter, "Enter")},
            {Key.NumpadDivide, new KeyDefinition("/", "/")},
            {Key.NumpadMultiply, new KeyDefinition("*", "*")},
            {Key.NumpadPlus, new KeyDefinition("+", "+")},
            {Key.NumpadMinus, new KeyDefinition("-", "-")},
            {Key.NumpadPeriod, new KeyDefinition(",", ",")},
            {Key.NumpadEquals, new KeyDefinition("=", "=")},
            {Key.Numpad0, new KeyDefinition("0", "0")},
            {Key.Numpad1, new KeyDefinition("1", "1")},
            {Key.Numpad2, new KeyDefinition("2", "2")},
            {Key.Numpad3, new KeyDefinition("3", "3")},
            {Key.Numpad4, new KeyDefinition("4", "4")},
            {Key.Numpad5, new KeyDefinition("5", "5")},
            {Key.Numpad6, new KeyDefinition("6", "6")},
            {Key.Numpad7, new KeyDefinition("7", "7")},
            {Key.Numpad8, new KeyDefinition("8", "8")},
            {Key.Numpad9, new KeyDefinition("9", "9")},
            {Key.F1, new KeyDefinition(Key.F1, "F1")},
            {Key.F2, new KeyDefinition(Key.F2, "F2")},
            {Key.F3, new KeyDefinition(Key.F3, "F3")},
            {Key.F4, new KeyDefinition(Key.F4, "F4")},
            {Key.F5, new KeyDefinition(Key.F5, "F5")},
            {Key.F6, new KeyDefinition(Key.F6, "F6")},
            {Key.F7, new KeyDefinition(Key.F7, "F7")},
            {Key.F8, new KeyDefinition(Key.F8, "F8")},
            {Key.F9, new KeyDefinition(Key.F9, "F9")},
            {Key.F10, new KeyDefinition(Key.F10, "F10")},
            {Key.F11, new KeyDefinition(Key.F11, "F11")},
            {Key.F12, new KeyDefinition(Key.F12, "F12")},
            {Key.OEM1, new KeyDefinition(">", "<")},
            {Key.OEM2, new KeyDefinition(Key.OEM2, "")},
            {Key.OEM3, new KeyDefinition(Key.OEM3, "")},
            {Key.OEM4, new KeyDefinition(Key.OEM4, "")},
            {Key.OEM5, new KeyDefinition(Key.OEM5, "")},
            {Key.IMESelected, new KeyDefinition(Key.IMESelected, "")}
        };
    }
}
